# Generated by Django 4.0.3 on 2022-03-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecritic_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
