# Generated by Django 4.0.3 on 2022-03-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecritic_site', '0002_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
