# Generated by Django 4.0.3 on 2022-03-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecritic_site', '0004_alter_game_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_genre',
        ),
        migrations.AddField(
            model_name='game',
            name='game_genre',
            field=models.ManyToManyField(to='gamecritic_site.genre'),
        ),
    ]
